version: 2
jobs:
  build:
    docker:
      - image: ellioseven/node:9
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
general:
  branches:
    only:
     - feature-circleci
